[workspace]
members = ["api", "models", "utils"]
resolver = "2"

[workspace.package]
authors = []
name = "synopic-backend"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
actix-web = "4"
tokio = { version = "1", features = ["full"] }